---
- name: Automate docker connection pipeline
  hosts: docker
  become: true
  vars_files: 
  - ./vars.yml

  tasks:
  - name: Docker Install
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable docker service
  service: 
    name: docker
    state: started
    enabled: true

- name: Build Docker Image
  command: "> docker build -t {{DOCKER_USERNAME}}/{{DOCKER_IMAGE}}:{{DOCKER_TAG}} /var/lib/jenkins/workspace/connect-ansible/Dockerfile"

- name: Docker Login 
  command: "> docker login -u sulav02 -p {{DOCKER_PASSWORD}} --no-interactive"

- name: Push Image to docker registry
  command: "> docker push {{DOCKER_USERNAME}}/{{DOCKER_IMAGE}}:{{DOCKER_TAG}}"

- name: Run docker container
  command: "> docker run -dit -p {{TARGET_PORT}}:{{DOCKER_CONTAINER_PORT}} --name {{DOCKER_CONTAINER_NAME}} {{DOCKER_USERNAME}}/{{DOCKER_IMAGE}}:{{DOCKER_TAG}}"


